package com.jeesuite.monitor.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseApp<M extends BaseApp<M>> extends Model<M> implements IBean {

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setNotifyEmails(java.lang.String notifyEmails) {
		set("notify_emails", notifyEmails);
	}

	public java.lang.String getNotifyEmails() {
		return get("notify_emails");
	}

	public void setMaster(java.lang.String master) {
		set("master", master);
	}

	public java.lang.String getMaster() {
		return get("master");
	}

	public void setMasterUid(java.lang.Integer masterUid) {
		set("master_uid", masterUid);
	}

	public java.lang.Integer getMasterUid() {
		return get("master_uid");
	}

	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}

	public java.lang.String getRemarks() {
		return get("remarks");
	}

}
