package com.jeesuite.monitor.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppConfig<M extends BaseAppConfig<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setAppName(java.lang.String appName) {
		set("app_name", appName);
	}

	public java.lang.String getAppName() {
		return get("app_name");
	}
	
	public void setEnv(java.lang.String env) {
		set("env", env);
	}

	public java.lang.String getEnv() {
		return get("env");
	}

	public void setVersion(java.lang.String appVersion) {
		set("version", appVersion);
	}

	public java.lang.String getVersion() {
		return get("version");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}
	
	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setContents(java.lang.String contents) {
		set("contents", contents);
	}

	public java.lang.String getContents() {
		return get("contents");
	}

	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}

	public java.util.Date getCreatedAt() {
		return get("created_at");
	}

	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}

	public java.util.Date getUpdatedAt() {
		return get("updated_at");
	}

	public void setCreatedBy(java.lang.Integer createdBy) {
		set("created_by", createdBy);
	}

	public java.lang.Integer getCreatedBy() {
		return get("created_by");
	}

	public void setUpdatedBy(java.lang.Integer updatedBy) {
		set("updated_by", updatedBy);
	}

	public java.lang.Integer getUpdatedBy() {
		return get("updated_by");
	}

}
