package com.jeesuite.monitor.model;

import com.jeesuite.monitor.model.base.BaseApp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class App extends BaseApp<App> {
	public static final App dao = new App();
}
