package com.jeesuite.monitor.model;

import com.jeesuite.monitor.model.base.BaseAppConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppConfig extends BaseAppConfig<AppConfig> {
	public static final AppConfig dao = new AppConfig();
}
