package com.jeesuite.monitor.model;

import com.jeesuite.monitor.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User();
}
